### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by FlorentCoppint** [petergeneric/unifi-protect-remux#15] opened 2021-09-17 16:14 UTC
Hi,
Doing remux on an ubv file from UDM Pro I got : 

```
2021/09/17 17:37:33 Analysing  14/68D79A8F74CB_0_rotating_1628893641320.ubv
2021/09/17 17:37:33 First Frame timestamp 2021-08-14 00:27:00.068 +0200 CEST
2021/09/17 17:37:33 First Frame timestamp 2021-08-14 00:27:00.023 +0200 CEST
2021/09/17 17:37:33 Second Frame timestamp 2021-08-14 00:27:00.023 +0200 CEST
panic: runtime error: integer divide by zero

goroutine 9 [running]:
ubvremux/ubv.extractTimecodeAndRate(0x40004d77c0, 0xa, 0xa, 0x40004d3b60, 0x5a, 0x400006c1e0)
	/opt/build-remux/unifi-protect-remux/ubv/ubvfile.go:111 +0x498
ubvremux/ubv.parseUbvInfo(0xffffc4dae09a, 0x2c, 0x40008c6080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/build-remux/unifi-protect-remux/ubv/ubvinfo.go:178 +0x354
ubvremux/ubv.runUbvInfo.func1(0xffffc4dae09a, 0x2c, 0x40008c6080, 0x400001e5d0)
	/opt/build-remux/unifi-protect-remux/ubv/ubvinfo.go:70 +0x38
created by ubvremux/ubv.runUbvInfo
	/opt/build-remux/unifi-protect-remux/ubv/ubvinfo.go:69 +0x1e8

```

First time I get this error. I run remux on another arm64 system than UDM, it was running fine until this file (many TB converted).

How can I debug ?

Thanks

**Comment by petergeneric** [comment] 2021-09-17 18:14
As a workaround, you can also force a framerate with the `-force-rate` argument (e.g. `-force-rate 25`)

However it'd be good to figure out what the underlying issue is and get it sorted - can you send me the output of running the ubnt_ubvinfo command against your .ubv just to make sure the output format hasn't changed?

Specifically:
`ubnt_ubvinfo -P -f file.ubv`

This should output quite a lot, so if you can redirect it to a file and attach it to this ticket that'd be helpful -- there's nothing confidential in the output, it's just a list of packet offsets and lengths.

I've had a few tickets lately where ubnt_ubvinfo has been returning errors, so I wonder if the UDMP versions are changing from the version I'm seeing on my Cloud Key v2

**Comment by FlorentCoppint** [comment] 2021-09-22 15:02
Hi,
Attached is the result of command you asked for.
Tell me if you see something wrong.
Thanks.
[68D79A8F74CB_0_rotating_1628893641320.txt](https://github.com/petergeneric/unifi-protect-remux/files/7211790/68D79A8F74CB_0_rotating_1628893641320.txt)

Florent

**Comment by petergeneric** [comment] 2021-09-22 17:01
Thanks - it looks like the duration of time between the first two video frames is too short which is tripping up my framerate estimation logic, so I'm going to leave this tagged as a bug and will aim to have a fix out shortly.

**Comment by petergeneric** [comment] 2021-09-22 23:26
This is causing a regression on timelapse test cases, so reworking that prior to a release

**Comment by petergeneric** [comment] 2021-09-22 23:52
Hi,

Can you please test with https://github.com/petergeneric/unifi-protect-remux/releases/tag/v3.0.3 and let me know how it goes?

**Comment by FlorentCoppint** [comment] 2021-09-23 09:52
Hi,
Thank you very much for your responsiveness.
It seems to work, but I now have the warning "Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps" on every file, is it expected ?
I have cameras recording at 24fps, some at 42, others at 48... is original frame rate is conserved ?
Thanks.
Florent

**Comment by FlorentCoppint** [comment] 2021-09-23 10:23
Hi,
Thank you very much for your responsiveness.
It seems to work, but I now have the warning "Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps" on every file, is it expected ?
On the problematic file "68D79A8F74CB_0_rotating_1628893641320", I got : Video Rate Probe: File appears to be 1 fps. Use -force-rate if incorrect.
I have this same warning on some files of a G4 Doorbell camera, recording at 45fps. Maybe format is different for that camera ?
Thanks
Florent

**Comment by petergeneric** [comment] 2021-09-23 10:26
Could you send me the ubnt_ubvinfo .txt file for any files that are giving you that warning? It should only be triggered for _timelapse_ files.

**Comment by FlorentCoppint** [comment] 2021-09-23 11:30
Here is an ubnt_ubvinfo .txt file giving the timelapse warning (I run it on "0_rotating" files, is it timelapse ?
[68D79A8F74CB_0_rotating_1628974295262.txt](https://github.com/petergeneric/unifi-protect-remux/files/7217219/68D79A8F74CB_0_rotating_1628974295262.txt)
).

**Comment by petergeneric** [comment] 2021-09-23 11:32
Ah apologies my last message didn't format correctly - timelapse files have `_timelapse_` in the filename.

Thanks for the .txt, I'll have a look at what's going on with it!

**Comment by FlorentCoppint** [comment] 2021-09-23 12:06
I don't want to convert _timelapse_ files. Only _rotating_ ones, and I get the timelapse warning on these.

**Comment by petergeneric** [comment] 2021-09-23 18:28
Apologies about that, I believe this new build should fix it - can you give it a try please before I run a proper release?

https://github.com/petergeneric/unifi-protect-remux/releases/tag/3.0.4-wip

**Comment by FlorentCoppint** [comment] 2021-09-25 12:35
Seems better, now have : Video Rate Probe: File appears to be 30 fps. Use -force-rate if incorrect.
Thank you a lot.

**Comment by petergeneric** [comment] 2021-09-25 12:38
Great - and I assume that's for a camera that's configured at 30fps? The .txt files you uploaded both were recognised at 45fps. I'll close this ticket now and run a release of 3.0.4.

Thanks for uploading those sample .txt files!

**Closed** 2021-09-25 12:38 UTC
Labels: bug

**Comment by FlorentCoppint** [comment] 2021-09-26 10:16
Yes, remux was running on 30 fps camera, it's ok for 45 & 48 fps ones too. :) 

By the way, I also have these 2 ffmpeg warnings : 
```
[aac @ 0xaaab015a47f0] Estimating duration from bitrate, this may be inaccurate
[mp4 @ 0xaaab014f26a0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
```
Is it a problem ? Do I have to open another issue ? That's not new, I always had this warnings without problem on final video file.

**Comment by petergeneric** [comment] 2021-09-26 10:18
Great.

Those FFmpeg warnings are nothing to worry about
